col_names <- names(binary)
binary[,col_names] <- lapply(binary[,col_names] , factor)
library(arules)
rules.all <- apriori(binary)
rules <- apriori(binary, control = list(verbose=F), parameter = list(minlen=2, supp=0.007, conf=0.8))
source("http://bioconductor.org/biocLite.R")
biocLite("Rgraphviz")
rules.sorted <- sort(rules, by="confidence")
inspect(rules.sorted)
library(arulesViz)
plot(rules.sorted)